spring.application.name=rrglass

# Banco de dados configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rrglass
spring.datasource.username=user
spring.datasource.password=user

# JPA não edita o schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# DESATIVA Flyway automático do Spring
spring.flyway.enabled=false

jwt.secret=U3VwZXJTZWNyZXRLZXlTdXBlclNlY3JldEtleQ==
jwt.expiration=86400000